In [229]:
import numpy as np

# http://www.blackarbs.com/blog/introduction-hidden-markov-models-python-networkx-sklearn/2/9/2017

In [244]:
def viterbi(O, S, pi, A, B):
    """
    O: observation space
    S: state space
    pi: initial probabilities
    y: sequence of observations
    A: transition matrix. 2d array with A[from_state][to_state]
    B: emission matrix. 2d array with B[state_i][observation_j]
    """
    
    K, T = len(S), len(O)
    
    # Stores the probability of the most likely path so far.
    T1 = np.zeros((K, T))
    
    # Stores the argmax of the most probable path.
    T2 = np.zeros((K, T))
    
    # Initial states for initial observation.
    T1[:, 0] = pi * B[:, O[0]]
    
    for j in range(1, T):
        for i in range(K):
            p = T1[:, j-1] * A[:, i]
            T1[i, j] = np.max(p * B[i, O[j]])
            T2[i, j] = np.argmax(p)
    
    # Paths.
    z = np.zeros(T).astype(np.int)
    z[-1] = np.argmax(T1[:, -1])
    
    for j in range(T-2, -1, -1):
        z[j] = T2[z[j+1], j+1]
    return z, T1, T2

In [247]:
states_dict = {
    0: 'healthy', 1: 'sick'
}
obs = [0,1,2] # 0: sleeping, 1: eating, 2: pooping
obs_space = [1,1,2,1,0,1,2,1,0,2,2,0,1,0,1]
obs_dict = {
    0: 'sleeping', 
    1: 'eating',
    2: 'pooping'
}
states = (0, 1) # healthy, sick
start_p = np.array([0.5, 0.5])
trans_p = np.array([[0.7, 0.3],
                    [0.4, 0.6]])
emit_p = np.array([[0.2, 0.6, 0.2],
                   [0.4, 0.1, 0.5]])

In [248]:
paths, _, _ = viterbi(obs, states, start_p, trans_p, emit_p)

print(paths)
for i, p in enumerate(paths):
    print(f'{obs_dict[obs[i]]:10} -> {states_dict[p]}')

[1 0 1]
sleeping   -> sick
eating     -> healthy
pooping    -> sick


In [258]:
obs = (0, 1, 2) # 0: normal, 1: cold, 2: dizzy
obs_map = {
    0: 'normal',
    1: 'cold',
    2: 'dizzy'
}
states_map = {
    0: 'Healthy',
    1: 'Fever'
}
states = (0, 1) # 0: Healthy, 1: Fever

# start_p[initial_state]
start_p = np.array([0.6, 0.4])

# trans_p[from_state][to_state]
trans_p = np.array([[0.7, 0.3],
                    [0.4, 0.6]])

# emit_p[state][observation]
emit_p = np.array([[0.5, 0.4, 0.1],
                   [0.1, 0.3, 0.6]])

paths, result, t2 = viterbi(obs, states, start_p, trans_p, emit_p)
for i, p in enumerate(paths):
    print(f'{obs_map[obs[i]]:8s} -> {states_map[states[p]]}')
print()
print(result)
print(t2)

normal   -> Healthy
cold     -> Healthy
dizzy    -> Fever

[[0.3     0.084   0.00588]
 [0.04    0.027   0.01512]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [259]:
obs = (0, 1, 2, 1, 2) # 0: normal, 1: cold, 2: dizzy
states = (0, 1) # 0: Healthy, 1: Fever

# start_p[initial_state]
start_p = np.array([0.6, 0.4])

# trans_p[from_state][to_state]
trans_p = np.array([[0.7, 0.3],
                    [0.4, 0.6]])

# emit_p[state][observation]
emit_p = np.array([[0.5, 0.4, 0.1],
                   [0.1, 0.3, 0.6]])

paths, result, t2 = viterbi(obs, states, start_p, trans_p, emit_p)
print(paths)
for i, p in enumerate(paths):
    print(f'{obs_map[obs[i]]:8s} -> {states_map[states[p]]}')
print()
print(result)
print(t2)

[0 0 1 1 1]
normal   -> Healthy
cold     -> Healthy
dizzy    -> Fever
cold     -> Fever
dizzy    -> Fever

[[3.00000e-01 8.40000e-02 5.88000e-03 2.41920e-03 1.69344e-04]
 [4.00000e-02 2.70000e-02 1.51200e-02 2.72160e-03 9.79776e-04]]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1.]]


In [260]:
obs = (0, 2, 1, 2, 1) # 0: normal, 1: cold, 2: dizzy
states = (0, 1) # 0: Healthy, 1: Fever

# start_p[initial_state]
start_p = np.array([0.6, 0.4])

# trans_p[from_state][to_state]
trans_p = np.array([[0.7, 0.3],
                    [0.4, 0.6]])

# emit_p[state][observation]
emit_p = np.array([[0.5, 0.4, 0.1],
                   [0.1, 0.3, 0.6]])

paths, result, t2 = viterbi(obs, states, start_p, trans_p, emit_p)
print(paths)
for i, p in enumerate(paths):
    print(f'{obs_map[obs[i]]:8s} -> {states_map[states[p]]}')
print()
print(result)
print(t2)

[0 1 1 1 1]
normal   -> Healthy
dizzy    -> Fever
cold     -> Fever
dizzy    -> Fever
cold     -> Fever

[[0.3        0.021      0.00864    0.0006048  0.00055987]
 [0.04       0.054      0.00972    0.0034992  0.00062986]]
[[0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 1.]]
